# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(475, 471)
        self.centralwidget = QtWidgets.QWidget(parent=Main)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_sayi1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.txt_sayi1.setGeometry(QtCore.QRect(120, 50, 31, 16))
        self.txt_sayi1.setObjectName("txt_sayi1")
        self.txt_sayi2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.txt_sayi2.setGeometry(QtCore.QRect(120, 90, 31, 16))
        self.txt_sayi2.setObjectName("txt_sayi2")
        self.lbl_sayi1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lbl_sayi1.setGeometry(QtCore.QRect(190, 50, 113, 21))
        self.lbl_sayi1.setObjectName("lbl_sayi1")
        self.lbl_sayi2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lbl_sayi2.setGeometry(QtCore.QRect(190, 90, 113, 21))
        self.lbl_sayi2.setObjectName("lbl_sayi2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 240, 41, 16))
        self.label.setObjectName("label")
        self.btn_topla = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_topla.setGeometry(QtCore.QRect(60, 170, 75, 24))
        self.btn_topla.setObjectName("btn_topla")
        self.btn_cikar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_cikar.setGeometry(QtCore.QRect(160, 170, 75, 24))
        self.btn_cikar.setObjectName("btn_cikar")
        self.btn_carp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_carp.setGeometry(QtCore.QRect(260, 170, 75, 24))
        self.btn_carp.setObjectName("btn_carp")
        self.btn_bol = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_bol.setGeometry(QtCore.QRect(360, 170, 75, 24))
        self.btn_bol.setObjectName("btn_bol")
        self.lbl_sonuc = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_sonuc.setGeometry(QtCore.QRect(170, 280, 161, 121))
        self.lbl_sonuc.setText("")
        self.lbl_sonuc.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lbl_sonuc.setObjectName("lbl_sonuc")
        Main.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 22))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Hesap Makinesi ac arslan usülü"))
        self.txt_sayi1.setText(_translate("Main", "Sayı1"))
        self.txt_sayi2.setText(_translate("Main", "Sayı2"))
        self.label.setText(_translate("Main", "Sonuç"))
        self.btn_topla.setText(_translate("Main", "Topla"))
        self.btn_cikar.setText(_translate("Main", "Çıkar"))
        self.btn_carp.setText(_translate("Main", "Çarp"))
        self.btn_bol.setText(_translate("Main", "Böl"))
